apiVersion: v1
kind: Pod
metadata:
  name: mininet
spec:
  containers:
  - name: mininet
    image: iwaseyusuke/mininet
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
